name: Demo Workflow with Manual Approval

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1-setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

  job2-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: job1-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run dummy tests
        run: |
          echo "Running tests..."
          sleep 5
          echo "Tests passed!"

  job3-lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: job2-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run linter
        run: |
          echo "Linting code..."
          sleep 2
          echo "Lint passed!"

  job4-build:
    name: Deploy Project (Manual Approval)
    runs-on: ubuntu-latest
    needs: job3-lint
    environment:
      name: production
      reviewers:
        - lavanya-sharma-clouddrove
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Waiting for manual approval..."
          echo "Deploying project..."
          sleep 3
          echo "Deployment complete!"
